name: Build and Test

on: pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    # needs: lint  # Lint 작업이 성공해야 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test